### PR TITLE
fix(GenerateConfigTask): use script relative path to fix a bug on window...

### LINKED ISSUE #1: Fails on Windows
There is a path issue on windows, where the slashes are mixed between the correct and the wrong ones

### PR DESCRIPTION
**Pull request by SchwingSK**
...s
(also works on *nix)

Closes #1

### CODE REVIEW

**Comment by pvdissel** [comment]
Thanks for your PR, I'll have a look at it this evening

**Comment by pvdissel** [comment]
@SchwingSK sorry it took so long, but I've just tested it and it works perfectly. Thank you so much :+1:

**Comment by SchwingSK** [comment]
No problem, glad it's merged!

**Comment by pvdissel** [comment]
Merged, and released :)
https://github.com/pvdissel/gradle-jenkins-jobdsl/releases/tag/v0.4.0

**Pull request merged**
